=== YULIYA2001/Java_XMLParsers/src/main/resources/plants.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="flowers">
    <xsd:complexType>
      <xsd:sequence>

        <xsd:element name="flower" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>

              <xsd:element name="name">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:pattern value="([A-Za-zА-Яа-я0-9]+[ -]?)+"/>
                    <xsd:minLength value="2"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>

              <xsd:element name="soil">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Грунтовая"/>
                    <xsd:enumeration value="Подзолистая"/>
                    <xsd:enumeration value="Дерново-подзолистая"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>

              <xsd:element name="country">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:pattern value="([A-Za-zА-Яа-я]+[ -]?)+"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>

              <xsd:element name="importDate" type="xsd:date"/>

              <xsd:choice>
                <!-- Растение без цветов -->
                <xsd:element name="visualParameters" type="visualParamsType"/>

                <!-- Растение с цветами -->
                <xsd:element name="extendedVisualParameters">
                  <xsd:complexType>
                    <xsd:complexContent>
                      <xsd:extension base="visualParamsType">
                        <xsd:sequence>
                          <xsd:element name="budColor" type="xsd:string"/>
                        </xsd:sequence>
                      </xsd:extension>
                    </xsd:complexContent>
                  </xsd:complexType>
                </xsd:element>

              </xsd:choice>

              <xsd:element name="growingTips">
                <xsd:complexType>
                  <xsd:sequence>

                    <xsd:element name="temperature">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:positiveInteger">
                          <xsd:minInclusive value="0"/>
                          <xsd:maxInclusive value="30"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>

                    <xsd:element name="lighting">
                      <xsd:complexType>
                        <xsd:attribute name="photophilous" use="optional" default="Да">
                          <xsd:simpleType>
                            <xsd:restriction>
                              <xsd:pattern value="Да|Нет"/>
                            </xsd:restriction>
                          </xsd:simpleType>
                        </xsd:attribute>
                      </xsd:complexType>
                    </xsd:element>

                    <xsd:element name="watering">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:positiveInteger">
                          <xsd:maxInclusive value="1000"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>

                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>

              <xsd:element name="multiplying">
                <xsd:simpleType>
                  <xsd:restriction>
                    <xsd:simpleType>
                      <xsd:list itemType="multiplyingType"/>
                    </xsd:simpleType>
                    <xsd:maxLength value="3"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>

            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:ID" use="required"/>
          </xsd:complexType>
        </xsd:element>

      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="multiplyingType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="Семена|Черенки|Листья"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="visualParamsType">
    <xsd:sequence>
      <xsd:element name="stemColor" type="xsd:string"/>
      <xsd:element name="leafColor" type="xsd:string"/>

      <xsd:element name="averageSize">
        <xsd:simpleType>
          <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="5"/>
            <xsd:maxInclusive value="100"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>

    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== YULIYA2001/Java_XMLParsers/src/main/resources/plants.xml
<?xml version='1.0' encoding="UTF-8"?>

<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="plants.xsd">


  <flower id="_1">

    <name>Хризантема кустовая Зембла белая</name>

    <soil>Подзолистая</soil>

    <origin>
      <country>Нидерланды</country>
      <importDate>2022-03-29</importDate>
    </origin>

    <extendedVisualParameters>
      <stemColor>Темно-зеленый</stemColor>
      <leafColor>Темно-зеленый</leafColor>
      <averageSize>50</averageSize>
      <budColor>Белый</budColor>
    </extendedVisualParameters>

    <growingTips>
      <temperature>17</temperature>
      <lighting photophilous="Да"/>
      <watering>500</watering>
    </growingTips>

    <multiplying>Черенки Семена</multiplying>

  </flower>

  <flower id="_2">
    <name>Тюльпан Barcelona</name>
    <soil>Грунтовая</soil>
    <origin>
      <country>Литва</country>
      <importDate>2022-03-30</importDate>
    </origin>
    <extendedVisualParameters>
      <stemColor>Фисташковый</stemColor>
      <leafColor>Темный пастельно-зеленый</leafColor>
      <averageSize>25</averageSize>
      <budColor>Желто-красный</budColor>
    </extendedVisualParameters>
    <growingTips>
      <temperature>18</temperature>
      <lighting photophilous="Да"/>
      <watering>210</watering>
    </growingTips>
    <multiplying>Семена</multiplying>
  </flower>

  <flower id="_3">
    <name>Орхидея Фаленопсис белая</name>
    <soil>Дерново-подзолистая</soil>
    <origin>
      <country>Турция</country>
      <importDate>2022-03-20</importDate>
    </origin>
    <extendedVisualParameters>
      <stemColor>Серо-зеленый</stemColor>
      <leafColor>Красного моря</leafColor>
      <averageSize>35</averageSize>
      <budColor>Белый</budColor>
    </extendedVisualParameters>
    <growingTips>
      <temperature>21</temperature>
      <lighting photophilous="Нет"/>
      <watering>200</watering>
    </growingTips>
    <multiplying>Черенки Семена</multiplying>
  </flower>

  <flower id="_4">
    <name>Гвоздика Red Soho</name>
    <soil>Грунтовая</soil>
    <origin>
      <country>Нидерланды</country>
      <importDate>2022-03-29</importDate>
    </origin>
    <extendedVisualParameters>
      <stemColor>Зеленый</stemColor>
      <leafColor>Зеленый</leafColor>
      <averageSize>45</averageSize>
      <budColor>Ярко красный</budColor>
    </extendedVisualParameters>
    <growingTips>
      <temperature>15</temperature>
      <lighting photophilous="Да"/>
      <watering>190</watering>
    </growingTips>
    <multiplying>Черенки</multiplying>
  </flower>

  <flower id="_5">
    <name>Фиалка Прекрасная креолка</name>
    <soil>Грунтовая</soil>
    <origin>
      <country>Беларусь</country>
      <importDate>2022-02-01</importDate>
    </origin>
    <extendedVisualParameters>
      <stemColor>Зеленый</stemColor>
      <leafColor>Темно-зеленый</leafColor>
      <averageSize>10</averageSize>
      <budColor>Темно-синий</budColor>
    </extendedVisualParameters>
    <growingTips>
      <temperature>24</temperature>
      <lighting photophilous="Да"/>
      <watering>100</watering>
    </growingTips>
    <multiplying>Листья Семена</multiplying>
  </flower>

  <flower id="_6">
    <name>Карликовый фикус пумила</name>
    <soil>Подзолистая</soil>
    <origin>
      <country>Китай</country>
      <importDate>2022-01-19</importDate>
    </origin>
    <visualParameters>
      <stemColor>Болотный</stemColor>
      <leafColor>Зеленый с белой оконтовкой</leafColor>
      <averageSize>17</averageSize>
    </visualParameters>
    <growingTips>
      <temperature>19</temperature>
      <lighting photophilous="Да"/>
      <watering>510</watering>
    </growingTips>
    <multiplying>Черенки</multiplying>
  </flower>

  <flower id="_7">
    <name>Эхинокактус</name>
    <soil>Дерново-подзолистая</soil>
    <origin>
      <country>США</country>
      <importDate>2021-12-09</importDate>
    </origin>
    <visualParameters>
      <stemColor>Светло-зеленый</stemColor>
      <leafColor>Оранжевый</leafColor>
      <averageSize>13</averageSize>
    </visualParameters>
    <growingTips>
      <temperature>25</temperature>
      <lighting photophilous="Да"/>
      <watering>50</watering>
    </growingTips>
    <multiplying>Семена</multiplying>
  </flower>

  <flower id="_8">
    <name>Алое пятнистое</name>
    <soil>Грунтовая</soil>
    <origin>
      <country>Литва</country>
      <importDate>2022-03-22</importDate>
    </origin>
    <visualParameters>
      <stemColor>Зеленый</stemColor>
      <leafColor>Зеленый с белыми пятнами</leafColor>
      <averageSize>30</averageSize>
    </visualParameters>
    <growingTips>
      <temperature>18</temperature>
      <lighting photophilous="Да"/>
      <watering>210</watering>
    </growingTips>
    <multiplying>Черенки</multiplying>
  </flower>

</flowers>
